# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='nombre',
            new_name='cliente',
        ),
    ]
