# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20180228_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='tipob',
            new_name='tipo_A',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipo',
        ),
    ]
