# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_item_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='item',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='item',
            name='producto',
        ),
        migrations.AlterField(
            model_name='item',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturas.Factura'),
            preserve_default=False,
        ),
    ]
