# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_auto_20180228_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='producto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturas.Producto'),
            preserve_default=False,
        ),
    ]
