# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-28 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_auto_20180228_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='factura',
            new_name='facturas',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='producto',
            new_name='productos',
        ),
    ]
